### ISSUE TITLE
Eventbrite sold out

### ISSUE THREAD

**Issue by taylorkline** [cityofaustin/hack-the-traffic#6]
![selection_021](https://cloud.githubusercontent.com/assets/2641739/23567446/dae2f8c2-001b-11e7-9e8a-cf2811fad3d3.png)

Is it actually all full?

**Comment by johnclary** [comment]
@jkdf2 we hit the max # of attendees we're allowed to have in the space. 

If you show up in-person without a registration we'll happily let you in if we have room. ( I strongly suspect we will)

Please come

**Comment by johnclary** [comment]
we had the event!
